### ISSUE TITLE
private ca stopped working with update HAOS 14.0

### ISSUE THREAD

**Issue by Dede1441** [Athozs/hass-additional-ca#13]
**Describe the issue**

I added a private CA a while ago, everything was working fine. I updated from gui to latest HAOS and the CA isn't anymore trusted, integration using https like adguard or frigate proxy stopped working.

I tried to uninstall the additionnal_ca integration, but also frigate proxy integration, without success.

**Describe your setup (please complete the following information):**

 - Installation type: HAOS
 - HAOS version (if applicable): 14.0
 - Home Assistant core version: 2024.12.1
 - Additional CA integration version:  0.2.4
 - Kind of certificate you use: private root ca

**YAML configuration extract**

```yaml
default_config:
...
additional_ca:
  my_private_ca: CA_VPN.crt
...
```

**Logs**

Supervisor logs :
```
2024-12-10 17:07:07.091 INFO (MainThread) [custom_components.additional_ca] my_private_ca (CA_VPN.crt) -> loaded.
2024-12-10 17:07:07.091 INFO (MainThread) [custom_components.additional_ca] Installation type = Home Assistant OS
2024-12-10 17:07:07.102 INFO (MainThread) [custom_components.additional_ca] Certifi bundle CA ready.
2024-12-10 17:07:07.124 INFO (MainThread) [custom_components.additional_ca] my_private_ca (CA_VPN.crt) -> loaded into Certifi CA bundle.
2024-12-10 17:07:07.124 INFO (MainThread) [homeassistant.setup] Setup of domain additional_ca took 0.29 seconds
```

Logs from frigate integration : 
```
Error fetching information from https://frigateale.onehome.lan:543/api/stats: Cannot connect to host frigateale.onehome.lan:543 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1020)')]
```

Debug from ha cli : 
![image](https://github.com/user-attachments/assets/6b3fab10-c782-4839-ad84-728755ca8af0)

Debug from another desktop in the same subnet, with the private CA : 
![image](https://github.com/user-attachments/assets/a3fd3a66-496a-4658-8d45-cf19d592fe29)

CA Validity : 
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 0 (0x0)
        Signature Algorithm: sha256WithRSAEncryption
        Issuer: CN=vpn.team-lcbs.eu, C=FR, ST=Basse Normandie, L=Mouen, O=HomeUsers, OU=HomeUsers
        Validity
            Not Before: Jul  5 08:33:06 2020 GMT
            Not After : Jul  3 08:33:06 2030 GMT
```
Frigate nginx server certificate validity :
```
   v:NotBefore: Jul 24 10:40:48 2024 GMT; NotAfter: Jun  7 10:40:48 2035 GMT
```

Clock properly setup on haos.

**Additional context**

 - What service/device are you trying to reach from Home Assistant with TLS/SSL ?

Adguard and Frigate server, Frigate behind nginx.

I have a second running instance of home assistant not updated and still working with this CA on another adguard/frigate server, using same king of certificates
Latest known version working :

Core 2024.11.3
Supervisor 2024.11.4
Operating System 13.2
User interface 20241106.2

**Comment by Dede1441** [comment]
Hi, 
Thank you for these informations.

Here is the output about the CA basic Constraints : 
![image](https://github.com/user-attachments/assets/3e819ea7-80de-4699-b4e7-6a990f36ac10)

And the one from the certificate frigate server : 

![image](https://github.com/user-attachments/assets/6c524a1e-2137-4f74-894c-e11c3826a265)

If i understand your feedback correctly, the CA cert should have a line with "critical" somewhere ?


This seem related :  [https://github.com/home-assistant/core/issues/132445](url) but ironically solved with additionnal_ca integration.

Thank you, i will wait for your feedback

**Comment by pc-bastler** [comment]
Hi, on my installation additional_CA also stopped working:

Core 2024.12.2
Supervisor 2024.11.4
Operating System 14.0
Frontend 20241127.7

Unfortunally I cannot find any Logs for the AddIn. I also cannot remember when exactly the Addin stopped working.

**Comment by pc-bastler** [comment]
Any news on this issue? - It's still persistent with 2015.1.0

`Logger: homeassistant.components.cert_expiry.coordinator
Quelle: components/cert_expiry/coordinator.py:48
Integration: Zertifikatsablauf (Dokumentation, Probleme)
Erstmals aufgetreten: 4. Januar 2025 um 23:59:42 (8 Vorkommnisse)
Zuletzt protokolliert: 4. Januar 2025 um 23:59:43

Certificate validation error: unifi.pxxxx.de [Missing Authority Key Identifier]
Certificate validation error: octoprint.pxxxxx.de [Missing Authority Key Identifier]
Certificate validation error: nas01.pxxxxxx.de [Missing Authority Key Identifier]
Certificate validation error: ha.pxxxxxxxx.de [Missing Authority Key Identifier]`

**Comment by singularity0821** [comment]
@Athozs I can confirm that it is working properly with Basic Constraints marked as critical.

**Comment by Dede1441** [comment]
I can also confirm it working, thank you @Athozs

**Comment by pc-bastler** [comment]
I do not understand the solution.

Do one really have to create a new Root- and new Intermediate Certificates and so need to swap out all client-Certificates out there?

**Comment by pc-bastler** [comment]
That unfortunately renders the extension unusable for me, since I cannot just create a new root with multiple issuing instances/CAs and 6 years worth of endpoint certificates and several of them shared with external partners :-(

It was a great and useful add in as long as it worked.
